rules:
  property-sort-order: 0
  no-color-literals: 0
  force-element-nesting: 0
  no-important: 0
  no-css-comments: 0
  single-line-per-selector: 0
  class-name-format: 0
  nesting-depth: 0
  no-qualifying-elements: 0
  force-pseudo-nesting: 0
  leading-zero: 0
  variable-name-format: 0
  mixin-name-format: 0
  zero-unit: 0
  pseudo-element: 0

